apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# =====================================================
# 1️⃣ Cluster Metadata
# =====================================================
metadata:
  name: subbu-cluster
  region: us-east-1
  version: "1.34"

# =====================================================
# 2️⃣ Existing VPC Configuration
# =====================================================
vpc:
  id: vpc-0abc123456789xyz   # <-- Replace with YOUR VPC ID

  subnets:
    private:
      us-east-1a:
        id: subnet-aaa111     # <-- Private subnet A
      us-east-1b:
        id: subnet-bbb222     # <-- Private subnet B

    public:
      us-east-1a:
        id: subnet-ccc333     # <-- Public subnet A
      us-east-1b:
        id: subnet-ddd444     # <-- Public subnet B

# =====================================================
# 3️⃣ IAM & OIDC (Required for IRSA)
# =====================================================
iam:
  withOIDC: true

# =====================================================
# 4️⃣ EKS Addons
# =====================================================
addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

# =====================================================
# 5️⃣ Managed Node Groups
# =====================================================
managedNodeGroups:

  # ---------------------------------------------------
  # 🟢 Application Node Group
  # ---------------------------------------------------
  - name: app-ng
    instanceType: t3.large
    desiredCapacity: 3
    minSize: 2
    maxSize: 6
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true

    labels:
      role: app

    tags:
      environment: production

  # ---------------------------------------------------
  # 🟣 Monitoring Node Group
  # ---------------------------------------------------
  - name: monitoring-ng
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true
    
    labels:
      role: monitoring

    taints:
      - key: monitoring
        value: "true"
        effect: NoSchedule

    tags:
      environment: production




# -----------------------------
# Command to run this file
# -----------------------------

# eksctl create cluster -f cluster.yaml
